### ISSUE TITLE
Yo como Dueño de mascota Quiero registrar mi mascota Para que pueda ser cuidada.

### ISSUE THREAD

**Issue by zeditio** [PupiUTN/Agiles#2]
# Tareas
- [x] Listado de Razas
- [ ] Textbox autocompletar razas
- [X] Listado de Tamanios
- [ ] Subir Imagen

# Criterios de Aceptacion

- [ ] Probar con todos los campos y pasa
- [ ] Probar con todo, menos la foto y el comentario adicional. Pasa
- [ ] Probar sin nombre o sin raza, o sin tamano, o sin vacunacion. No pasa
