### ISSUE TITLE
Buscar cuidadores por Ubicación

### ISSUE THREAD

**Issue by jorgecons** [PupiUTN/Agiles#30]
Yo como dueño de perro  
quiero buscar cuidadores por ubicación  
para poder pedir solicitud de reserva  
### Criterios
Buscar por ciudad y localidad
Seleccionar provincia e introducir al menos 3 letras de localidad
Se debe poder ordenar por tamaño de perro y cantidad
### Tareas
- [ ]  Buscar base de datos de provincia y localidades.
- [ ] Agregar a base de datos nuestra.
- [ ] Agregar clases, tanto dominio como persistencia.
- [ ] Refactorizar Clase Dirección
- [ ] Refactorizar Registro de Cuidador FrontEnd.
- [ ] Refactorizar Registro de Cuidador BackEnd.
- [ ] Actualizar script carga de datos en bd.
- [ ] Realizar FrontEnd de ordenadores.
- [ ] Actualizar BackEnd
